version: '3.6'
networks:
  default:
    name: my-net
    external: true

services:
  user-service:
    container-name: user-service
    image: <host>:<port>/user_service:latest
    volumes:
      - <local>:<docker>
    ports:
      - 0.0.0.0:8088:8000
      - 0.0.0.0:50051:50051
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DB_HOST=my-postgres
      - DB_PORT=5432
      - DB_NAME=user_db
      - DB_USERNAME=user_service
      - DB_PASSWORD=${USER_DB_PASS}
  
  chat-service:
    container-name: chat-service
    image: <host>:<port>/chat_service:latest
    volumes:
      - <local>:<docker>
    ports:
      - 0.0.0.0:8089:8000
      - 0.0.0.0:50052:50051
    environment:
      - MONGO_HOST=my-mongo
      - MONGO_DB=mongo_db
      - MONGO_USER=ngochm
      - MONGO_PASS=${MONGO_DB_PASS}
      - REDIS_HOST=my-redis
